# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name:'Chicago' }, { name:'Copenhagen' }])
#   Mayor.create(name:'Emanuel', city: cities.first)

Role.create([{name:'Admin'}, {name:'Customer'}, {name:'VenueOwner'}])

User.create([{email:'rnarayana@live.com', password:'pinngs7123', password_confirmation:'pinngs7123', role_ids:'1'}])

Area.create([{area1:'Adambakkam', area2:'Alandur', distance:'1.5'}])
Area.create([{area1:'Adambakkam', area2:'Guindy', distance:'3.5'}])
Area.create([{area1:'Adambakkam', area2:'Madipakkam', distance:'4'}])
Area.create([{area1:'Adambakkam', area2:'Meenambakkam', distance:'4.2'}])
Area.create([{area1:'Adambakkam', area2:'St. Thomas Mount', distance:'2'}])
Area.create([{area1:'Adyar', area2:'Besant Nagar', distance:'1.5'}])
Area.create([{area1:'Adyar', area2:'ECR', distance:'2'}])
Area.create([{area1:'Adyar', area2:'OMR', distance:'4'}])
Area.create([{area1:'Adyar', area2:'Taramani', distance:'3.5'}])
Area.create([{area1:'Adyar', area2:'Thiruvanmiyur', distance:'2.8'}])
Area.create([{area1:'Alandur', area2:'Adambakkam', distance:'1.5'}])
Area.create([{area1:'Alandur', area2:'Guindy', distance:'1.5'}])
Area.create([{area1:'Alandur', area2:'Madipakkam', distance:'6'}])
Area.create([{area1:'Alandur', area2:'Meenambakkam', distance:'4'}])
Area.create([{area1:'Alandur', area2:'St. Thomas Mount', distance:'1.7'}])
Area.create([{area1:'Alwarpet', area2:'Mandaveli', distance:'2.3'}])
Area.create([{area1:'Alwarpet', area2:'Mylapore', distance:'2'}])
Area.create([{area1:'Alwarpet', area2:'R.A.Puram', distance:'2'}])
Area.create([{area1:'Alwarpet', area2:'T.Nagar', distance:'2.7'}])
Area.create([{area1:'Alwarpet', area2:'Teynampet', distance:'2.3'}])
Area.create([{area1:'Ambattur', area2:'Anna Nagar', distance:'6'}])
Area.create([{area1:'Ambattur', area2:'Avadi', distance:'4.9'}])
Area.create([{area1:'Ambattur', area2:'Kolathur', distance:'7'}])
Area.create([{area1:'Ambattur', area2:'Korattur', distance:'8'}])
Area.create([{area1:'Ambattur', area2:'Mogappair', distance:'4.8'}])
Area.create([{area1:'Aminjikarai', area2:'Anna Nagar', distance:'6'}])
Area.create([{area1:'Aminjikarai', area2:'Arumbakkam', distance:'2.8'}])
Area.create([{area1:'Aminjikarai', area2:'Choolaimedu', distance:'1.5'}])
Area.create([{area1:'Aminjikarai', area2:'Koyambedu', distance:'5'}])
Area.create([{area1:'Aminjikarai', area2:'Nungambakkam', distance:'2.5'}])
Area.create([{area1:'Anna Nagar', area2:'Aminjikarai', distance:'6'}])
Area.create([{area1:'Anna Nagar', area2:'Arumbakkam', distance:'3.6'}])
Area.create([{area1:'Anna Nagar', area2:'Aynavaram', distance:'5.3'}])
Area.create([{area1:'Anna Nagar', area2:'Koyambedu', distance:'3.6'}])
Area.create([{area1:'Anna Nagar', area2:'Mogappair', distance:'5.5'}])
Area.create([{area1:'Arumbakkam', area2:'Aminjikarai', distance:'2.8'}])
Area.create([{area1:'Arumbakkam', area2:'Anna Nagar', distance:'3.6'}])
Area.create([{area1:'Arumbakkam', area2:'Chetpet', distance:'5.2'}])
Area.create([{area1:'Arumbakkam', area2:'Choolaimedu', distance:'3.5'}])
Area.create([{area1:'Arumbakkam', area2:'Koyambedu', distance:'3.3'}])
Area.create([{area1:'Ashok Nagar', area2:'Jafferkhanpet', distance:'2.2'}])
Area.create([{area1:'Ashok Nagar', area2:'K.K.Nagar', distance:'1.5'}])
Area.create([{area1:'Ashok Nagar', area2:'Kodambakkam', distance:'3.3'}])
Area.create([{area1:'Ashok Nagar', area2:'Vadapalani', distance:'1.7'}])
Area.create([{area1:'Ashok Nagar', area2:'West Mambalam', distance:'2.6'}])
Area.create([{area1:'Avadi', area2:'Ambattur', distance:'4.9'}])
Area.create([{area1:'Avadi', area2:'Korattur', distance:'15'}])
Area.create([{area1:'Avadi', area2:'Mogappair', distance:'9'}])
Area.create([{area1:'Avadi', area2:'Poonamallee', distance:'10'}])
Area.create([{area1:'Avadi', area2:'Villivakkam', distance:'12'}])
Area.create([{area1:'Aynavaram', area2:'Anna Nagar', distance:'5.3'}])
Area.create([{area1:'Aynavaram', area2:'Mogappair', distance:'10'}])
Area.create([{area1:'Aynavaram', area2:'Perambur', distance:'3.4'}])
Area.create([{area1:'Aynavaram', area2:'Purasawalkam', distance:'3'}])
Area.create([{area1:'Aynavaram', area2:'Villivakkam', distance:'5'}])
Area.create([{area1:'Besant Nagar', area2:'Adyar', distance:'1.5'}])
Area.create([{area1:'Besant Nagar', area2:'ECR', distance:'2.8'}])
Area.create([{area1:'Besant Nagar', area2:'OMR', distance:'4'}])
Area.create([{area1:'Broadway', area2:'Park Town', distance:'3'}])
Area.create([{area1:'Chetpet', area2:'Egmore', distance:'2.7'}])
Area.create([{area1:'Choolaimedu', area2:'Aminjikarai', distance:'1.5'}])
Area.create([{area1:'Choolaimedu', area2:'Arumbakkam', distance:'3.5'}])
Area.create([{area1:'Choolaimedu', area2:'Nungambakkam', distance:'3'}])
Area.create([{area1:'Chrompet', area2:'Pammal', distance:'6'}])
Area.create([{area1:'ECR', area2:'Adyar', distance:'2'}])
Area.create([{area1:'ECR', area2:'Besant Nagar', distance:'2.8'}])
Area.create([{area1:'ECR', area2:'Thiruvanmiyur', distance:'3'}])
Area.create([{area1:'Egmore', area2:'Chetpet', distance:'3'}])
Area.create([{area1:'Ekkaduthangal', area2:'Alandur', distance:'3'}])
Area.create([{area1:'Guindy', area2:'Alandur', distance:'1.5'}])
Area.create([{area1:'Jafferkhanpet', area2:'Ashok Nagar', distance:'2.2'}])
Area.create([{area1:'K.K.Nagar', area2:'Ashok Nagar', distance:'1.5'}])
Area.create([{area1:'Kelambakkam', area2:'Sholinganallur', distance:'5'}])
Area.create([{area1:'Kilpauk', area2:'Chetpet', distance:'2'}])
Area.create([{area1:'Kodambakkam', area2:'T.Nagar', distance:'2'}])
Area.create([{area1:'Korattur', area2:'Ambattur', distance:'8'}])
Area.create([{area1:'Kotturpuram', area2:'Adyar', distance:'2'}])
Area.create([{area1:'Koyambedu', area2:'Aminjikarai', distance:'5'}])
Area.create([{area1:'Koyambedu', area2:'Anna Nagar', distance:'3.6'}])
Area.create([{area1:'Koyambedu', area2:'Arumbakkam', distance:'3.3'}])
Area.create([{area1:'Koyambedu', area2:'Vadapalani', distance:'3'}])
Area.create([{area1:'Madipakkam', area2:'Adambakkam', distance:'4'}])
Area.create([{area1:'Madipakkam', area2:'Alandur', distance:'6'}])
Area.create([{area1:'Mahabalipuram', area2:'Kelambakkam', distance:'20'}])
Area.create([{area1:'Mandaveli', area2:'Alwarpet', distance:'2.3'}])
Area.create([{area1:'Mandaveli', area2:'R.A.Puram', distance:'2'}])
Area.create([{area1:'Meenambakkam', area2:'Alandur', distance:'4'}])
Area.create([{area1:'Meenambakkam', area2:'Guindy', distance:'3'}])
Area.create([{area1:'Mogappair', area2:'Ambattur', distance:'4.8'}])
Area.create([{area1:'Mogappair', area2:'Anna Nagar', distance:'5.5'}])
Area.create([{area1:'Mylapore', area2:'Alwarpet', distance:'2'}])
Area.create([{area1:'Mylapore', area2:'Mandaveli', distance:'2'}])
Area.create([{area1:'Nungambakkam', area2:'Aminjikarai', distance:'2.5'}])
Area.create([{area1:'Nungambakkam', area2:'Chetpet', distance:'3'}])
Area.create([{area1:'Pallavaram', area2:'Chrompet', distance:'2'}])
Area.create([{area1:'Park Town', area2:'Washermanpet', distance:'3'}])
Area.create([{area1:'Perambur', area2:'Aynavaram', distance:'3.4'}])
Area.create([{area1:'Perungulathur', area2:'Vandalur', distance:'2'}])
Area.create([{area1:'Poonamallee', area2:'Avadi', distance:'10'}])
Area.create([{area1:'Poonamallee', area2:'Porur', distance:'3'}])
Area.create([{area1:'Purasawalkam', area2:'Aynavaram', distance:'3'}])
Area.create([{area1:'R.A.Puram', area2:'Alwarpet', distance:'2'}])
Area.create([{area1:'R.A.Puram', area2:'Mylapore', distance:'2'}])
Area.create([{area1:'Ramapuram', area2:'Porur', distance:'3'}])
Area.create([{area1:'Saidapet', area2:'Guindy', distance:'3'}])
Area.create([{area1:'Santhome', area2:'Mylapore', distance:'3'}])
Area.create([{area1:'Sriperumbudur', area2:'Poonamallee', distance:'15'}])
Area.create([{area1:'St. Thomas Mount', area2:'Adambakkam', distance:'2'}])
Area.create([{area1:'St. Thomas Mount', area2:'Alandur', distance:'1.7'}])
Area.create([{area1:'St. Thomas Mount', area2:'Guindy', distance:'2'}])
Area.create([{area1:'T.Nagar', area2:'Alwarpet', distance:'2.7'}])
Area.create([{area1:'T.Nagar', area2:'West Mambalam', distance:'1'}])
Area.create([{area1:'Tambaram', area2:'Perungulathur', distance:'3'}])
Area.create([{area1:'Taramani', area2:'Adyar', distance:'3.5'}])
Area.create([{area1:'Taramani', area2:'Thiruvanmiyur', distance:'2'}])
Area.create([{area1:'Teynampet', area2:'Alwarpet', distance:'2.3'}])
Area.create([{area1:'Thiruvanmiyur', area2:'Adyar', distance:'2.8'}])
Area.create([{area1:'Vadapalani', area2:'Ashok Nagar', distance:'1.7'}])
Area.create([{area1:'Villivakkam', area2:'Aynavaram', distance:'5'}])
Area.create([{area1:'West Mambalam', area2:'Ashok Nagar', distance:'2.6'}])